import Head from 'next/head'
import Nav from '@/components/nav'
import Hero from '@/components/hero'
import AboutSection from '@/components/aboutSection'
import BlogSection from '@/components/blogSection'
import Footer from '@/components/footer'
import background from "@/assets/background.jpg"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mb-space-y-20 overflow-hidden sm:space-y-32 md:space-y-40">
        <header className="relative">
          <div className="px-4 sm:px-6 md:px-8">
          <div className="absolute inset-0 bottom-10  bg-no-repeat bg-slate-50 dark:bg-[#0B1120] background-theme bg-cover"
                style={{backgroundImage:`url(${background.src})`}}
                // style="background-image: url(./background.jpg);background-size: cover; background-repeat: no-repeat;"
                >
                    <div className="absolute inset-0 bg-grid-slate-900/[0.04] bg-[bottom_1px_center] dark:bg-grid-slate-400/[0.05] dark:bg-bottom"
                        // style="mask-image:linear-gradient(to bottom, transparent, black);-webkit-mask-image:linear-gradient(to bottom, transparent, black)"
                        >
                    </div>
                </div>
            <Nav />
            <Hero />
          </div>
        </header>
      </div>

      <AboutSection />
      <BlogSection />
      <Footer />

    </>
  )
}
