import Article from "@/components/article";
import Footer from "@/components/footer";
import Nav from "@/components/nav";
import Head from "next/head";

export default function Blog() {
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="space-y-20 overflow-hidden sm:space-y-32 md:space-y-40">
            <header className="relative">
                <div className="px-4 sm:px-6 md:px-8">
                    <Nav />
                </div>
            </header>
        </div>

        <section className="w-full px-4 py-24 mx-auto max-w-7xl md:w-3/4 lg:w-2/4 bg-white dark:bg-slate-900">
            <div className="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
                <h2 className="mb-4 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Our Blog
                </h2>
                <p className="font-light text-gray-500 sm:text-xl dark:text-gray-400">We use an agile approach to test
                    assumptions and connect with the needs of your audience early and often.</p>
            </div>
            <div className="flex flex-col space-y-12 divide-y divide-gray-800">
                {/* <Blog />
                <Blog />
                <Blog />
                <Blog /> */}
                <Article/>
                <Article/>
                <Article/>

            </div>
            <div
                className="flex flex-col items-center justify-center pt-12 mt-12 space-x-0 space-y-2 border-t border-gray-800 md:space-x-2 md:space-y-0 md:flex-row">
                <a href="#"
                    className="inline-flex items-center font-medium text-primary-600 dark:text-primary-500 hover:underline">Previous
                    Page
                </a>
                <a href="#"
                    className="inline-flex items-center font-medium text-primary-600 dark:text-primary-500 hover:underline">Next
                    Page
                </a>
            </div>
        </section>
        <Footer />
    </>
}